feat: benchmarking (#999)
* feat: add benchmarking dashboard, CI hook on PR, and store lifetime results

* refactor: change python env to 3.13 in benchmarks

* refactor: add verbosity, use 3.11 for benchmarking

* fix: OSError: [Errno 7] Argument list too long

* refactor: add debug statements

* refactor: remove extraneous -e

* refactor: fix tests and linter errors

* fix: track main package in coverage

* refactor: fix test coverage testing

* refactor: fix repo owner name in benchmark on pushing comment

* refactor: add asv monkeypatch to docs workflow

* refactor: temporarily allow building docs in forks

* refactor: use py 3.13 for benchmarking

* refactor: run only a single benchmark for PRs to speed them up

* refactor: install asv in the docs build workflow

* refactor: use hatch docs env to generate benhcmarks in docs CI

* refactor: more trying

* refactor: move tests

* Add benchmark results for 0.137

* Trigger Build

* Add benchmark results for 0.138

* refactor: set constant machine name when benchmarking

* Add benchmark results for 0.139

* refactor: fix issue with paths too long

* Add benchmark results for 0.140

* docs: update comment

* refactor: remove test benchmarking data

* refactor: fix comment

* refactor: allow the benchmark workflow to write to PRs

* refactor: use personal access token to set up the PR benchmark bot

* refactor: split the benchmark PR flow into two to make it work with PRs from forks

* refactor: update deprecated actions/upload-artifact@v3 to v4

* refactor: fix missing directory in benchmarking workflow

* refactor: fix triggering of second workflow

* refactor: fix workflow finally?

* docs: add comments to cut-offs and direct people to benchmarks PR

---------

Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -9,11 +9,6 @@ on:
       - '[0-9]+.[0-9]+.[0-9]+'
     branches: 
       - master
-  pull_request:
-      branches:
-      - main
-  release:
-    types: [published]
   workflow_dispatch:
 
 jobs:
@@ -27,29 +22,115 @@ jobs:
     # Only run in original repo (not in forks)
     if: github.repository == 'django-components/django-components'
     steps:
+
+      ##############################
+      # SETUP
+      ##############################
+
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.12"
+          python-version: "3.13"
+          cache: 'pip'
 
       - name: Install Hatch
         run: |
             python -m pip install --upgrade pip wheel
-            python -m pip install -q hatch pre-commit
+            python -m pip install -q hatch pre-commit asv
             hatch --version
-
-      - name: Create Virtual Environment
-        run: hatch env create docs
 
       - name: Configure git
         run: |
+          # Get the master branch so we can run benchmarks on it
+          git remote add upstream https://github.com/${{ github.repository }}.git
+          git fetch origin master:master
+          git checkout master
+
           # required for "mike deploy" command below which pushes to gh-pages
           git config user.name github-actions
           git config user.email github-actions@github.com
+
+      ###########################################
+      # RECORD BENCHMARK - ONLY ON PUSH TO MASTER
+      ###########################################
+
+      - name: Run benchmarks for tag
+        if: github.ref_type == 'tag' && github.event_name == 'push'
+        run: |
+          # Get tag name
+          TAG=${GITHUB_REF#refs/tags/}
+          echo "TAG: $TAG"
+
+          # TODO: REMOVE ONCE FIXED UPSTREAM
+          # Fix for https://github.com/airspeed-velocity/asv_runner/issues/45
+          # Prepare virtual environment
+          # Currently, we have to monkeypatch the `timeit` function in the `timeraw` benchmark.
+          # The problem is that `asv` passes the code to execute via command line, and when the
+          # code is too big, it fails with `OSError: [Errno 7] Argument list too long`.
+          # So we have to tweak it to pass the code via STDIN, which doesn't have this limitation.
+          #
+          # 1. First create the virtual environment, so that asv generates the directories where
+          #    the monkeypatch can be applied.
+          echo "Creating virtual environment..."
+          asv setup -v || true
+          echo "Virtual environment created."
+          # 2. Now let's apply the monkeypatch by appending it to the `timeraw.py` files.
+          # First find all `timeraw.py` files
+          echo "Applying monkeypatch..."
+          find .asv/env -type f -path "*/site-packages/asv_runner/benchmarks/timeraw.py" | while read -r file; do
+              # Add a newline and then append the monkeypatch contents
+              echo "" >> "$file"
+              cat "benchmarks/monkeypatch_asv_ci.txt" >> "$file"
+          done
+          echo "Monkeypatch applied."
+          # END OF MONKEYPATCH
+
+          # Prepare the profile under which the benchmarks will be saved.
+          # We assume that the CI machine has a name that is unique and stable.
+          # See https://github.com/airspeed-velocity/asv/issues/796#issuecomment-1188431794
+          echo "Preparing benchmarks profile..."
+          asv machine --yes --machine ci-linux
+          echo "Benchmarks profile DONE."
+
+          # Run benchmarks for the current tag
+          # - `^` means that we mean the COMMIT of the tag's branch, not the BRANCH itself.
+          #       Without it, we would run benchmarks for the whole branch history.
+          #       With it, we run benchmarks FROM the tag's commit (incl) TO ...
+          # - `!` means that we want to select range spanning a single commit.
+          #       Without it, we would run benchmarks for all commits FROM the tag's commit
+          #       TO the start of the branch history.
+          #       With it, we run benchmarks ONLY FOR the tag's commit.
+          echo "Running benchmarks for tag ${TAG}..."
+          asv run master^! -v
+          echo "Benchmarks for tag ${TAG} DONE."
+
+          # Generate benchmarks site
+          # This should save it in `docs/benchmarks/`, so we can then use it when
+          # building docs site with `mkdocs`.
+          echo "Generating benchmarks site..."
+          asv publish
+          echo "Benchmarks site DONE."
+
+          # Stage and commit benchmark results
+          echo "Staging and committing benchmark results..."
+          git add .asv/results/
+          git add docs/benchmarks/
+          git commit -m "Add benchmark results for ${TAG}"
+          echo "Benchmark results committed."
+          git push origin master
+          echo "Benchmark results pushed to master."
+
+      ##############################
+      # BUILD & DEPLOY DOCS
+      ##############################
+
+      - name: Create Virtual Environment
+        run: hatch env create docs
 
       # Conditions make sure to select the right step, depending on the job trigger.
       # Only one of the steps below will run at a time. The others will be skipped.
@@ -69,12 +150,6 @@ jobs:
 
       - name: Build & deploy docs for a new tag
         if: github.ref_type == 'tag' && github.event_name == 'push'
-        run: |
-          hatch run docs:mike deploy --push --update-aliases ${{ github.ref_name }} latest
-          hatch run docs:mike set-default latest --push
-
-      - name: Build & deploy docs for a new release
-        if: github.event_name == 'release'
         run: |
           hatch run docs:mike deploy --push --update-aliases ${{ github.ref_name }} latest
           hatch run docs:mike set-default latest --push
